name: kuharko
description: Flutter application for checking out cool recipes
publish_to: 'none'
version: 2.1.1+211

#
# DEPLOYING APP
# 1. `pubspec.yaml` -> Bump version number
# 2. `release_notes.txt` -> Update changelog for all languages
# 3. `default.txt` -> Update changelog for all languages
#

#
# Android
# `cd android/ && fastlane play_store_release`
#
# GitHub Releases
# `cd android/ && fastlane github_release`
#
# iOS
# `cd ios/ && fastlane app_store_release`
#

environment:
  sdk: 3.9.2

dependencies:
  flutter:
    sdk: flutter

  animations: 2.1.0
  cached_network_image: 3.4.1
  dio: 5.9.0
  dough: 2.0.0
  envied: 1.3.1
  flutter_animate: 4.5.2
  flutter_displaymode: 0.7.0
  flutter_native_splash: 2.4.6
  flutter_spinkit: 5.2.2
  flutter_staggered_animations: 1.1.1
  flutter_web_browser: 0.17.3
  get: 4.7.2
  google_nav_bar: 5.0.7
  just_audio: 0.10.5
  logger: 2.6.2
  shared_preferences: 2.5.3
  url_launcher: 6.3.2

dev_dependencies:
  build_runner: 2.9.0
  envied_generator: 1.3.1
  flutter_launcher_icons: 0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/bottom/
    - assets/icons/categories/
    - assets/icons/illustrations/
    - assets/icons/home_recipe/
    - assets/icons/recipe/
    - assets/icons/results/
    - assets/icons/search/
    - assets/images/
    - assets/boom.wav
    - .env

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSansRegular.ttf
          weight: 500
        - asset: assets/fonts/ProductSansBold.ttf
          weight: 700

# Run code generation - `dart run build_runner build -d`

# Configuration for 'flutter_launcher_icons'
# Run icon generation with 'dart run flutter_launcher_icons:main'
flutter_launcher_icons:
  image_path_android: 'assets/icon.png'
  image_path_ios: 'assets/icon.png'
  android: true
  ios: true
  adaptive_icon_background: "assets/background.png"
  adaptive_icon_foreground: "assets/splash_icon.png"
  adaptive_icon_foreground_inset: 16
  adaptive_icon_monochrome: "assets/monochrome.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: '#ffffff'
  image_path_ios_dark_transparent: "assets/icon_dark.png"
  image_path_ios_tinted_grayscale: "assets/icon_tinted.png"
  web:
    generate: true
    image_path: 'assets/icon.png'
    background_color: '#ffffff'
    theme_color: '#ffffff'
  windows:
    generate: true
    image_path: 'assets/icon.png'
    icon_size: 48
  macos:
    generate: true
    image_path: 'assets/icon.png'

# Configuration for 'flutter_native_splash'
# Run splash screen generation with 'dart run flutter_native_splash:create'
flutter_native_splash:
  background_image: 'assets/splash.png'
  background_image_dark: 'assets/splash.png'
  android_12:
    image: 'assets/splash_icon.png'
    color: '#ffffff'
    image_dark: 'assets/splash_icon.png'
    color_dark: '#1F1D2B'
